module YbLoggers::LogEventCodes

  CASH_LIST_ERROR = 'CLE001'
  NOTICE_LIST_ERROR = 'NLE001'
  TRAVEL_POST_LIST_ERROR = 'TPLE001'
  SOCIAL_SIGN_IN_ERROR = 'SSE001'
  VALID_TOKEN_ERROR = 'VTE001'
  TOKEN_IS_EXPIRED =  'TE001'
  DECODE_ACCESS_TOKEN_ERROR = 'DATE001'
  AUTHENTICATE_ERROR = 'AE001'
end